name: Docker CI
on:
  push:
    branches:
      - master
env:
  DOCKER_BUILDKIT: 1
  LATEST_TAG: 24.0.1
jobs:
  build:
    name: Build and push to Docker Hub
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - "24.0.1"
          - "23.1"
          - "23.0"
          - "22.1"
          - "22.0"
          - "0.21.2"
          - "0.21.1"
          - "0.21.0"
          - "0.20.2"
          - "0.20.1"
          - "0.20.0"
          - "0.19.1"
          - "0.19.0.1"
          - "0.18.1"
          - "0.18.0"
          - "0.17.2"
          - "0.17.1"
          - "0.17.0.1"
          - "0.17.0"
          - "0.16.3"
          - "0.15.2"
          - "0.14.3"
          - "0.13.2"
          - "0.13.1"
          - "0.13.0"
    steps:
      - uses: actions/checkout@v1
  
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Setup Docker buildx
        run: docker buildx create --use

      - name: Run Docker buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${{matrix.version}} \
            --tag ${{ secrets.DOCKER_USERNAME }}/bitcoind:v${{matrix.version}} \
            --push .

      - name: Rebuild for latest tag
        if: matrix.version == env.LATEST_TAG
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${{matrix.version}} \
            --tag ${{ secrets.DOCKER_USERNAME }}/bitcoind:latest \
            --push .
